### ISSUE TITLE
Script extract_duplicates returned NaN duplication rate

### ISSUE THREAD

**Issue by NgocTNguyen** [vibansal/PCRduplicates#1]
I ran ./extract_duplicates to estimate PCR duplication rate on our data:
./extract_duplicates --bam SRR1585519.dedup.merged.sorted.bam --VCF NA19099.het.vcf --mmq 20 > SRR1585519.dedup.hetreads

however it returned:
PCR duplicates marked 0 total-reads 0 frac nan discarded 62152388
#clusters 
total reads (PE=1) 0 unique-reads 0 duplicates:0, duplication rate nan 

Using samtool rmdup and IGV, we observed a lot of duplicate reads in our data, but the script here seemed to not work on our files. What's the problem here?

**Comment by bansal-lab** [comment]
is the data single-end reads ? If so, please use the "--singlereads 1" option.

**Comment by NgocTNguyen** [comment]
I did add "--singlereads 1" in our command line, but the output was still the same.
I ran the script on another input file (PE reads) and did get the output file. So there is an issue of the script to take a SE file as an input.
However, when I ran the next script ./estimate_PCRduprate.py I got this output: 

identified 0 het variants filtered 0 high-cov 1e-07 0.0 0.0 0.0
Traceback (most recent call last):
  File "estimate_PCRduprate.py", line 407, in <module>
    [Frate,Ftotal,Funique,Funiqlist] = calculate_values(duplicate_counts,cluster_counts); 
  File "estimate_PCRduprate.py", line 103, in calculate_values
    p = float(AB_counts[0])/(AB_counts[0] + AB_counts[1]); 
ZeroDivisionError: float division by zero

How could it be "identified 0 het variants" ?
